apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [/bin/echo]
      args: ["$(params.message)"]

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    name: source
  params:
    - name: args
      description: The nosetest is getting arguments
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspace.source.path)
      script: |
         #!/bin/bash
         set -e 
         python -m pip install -U pip wheel
         python install -r requirements.txt
         nosetests $(params.options)
